version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order
    environment:
      - PORT=3003

  auth:
    build: ./auth
    container_name: auth
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_AUTH_URI=mongodb://mongo/auth
    depends_on:
      - mongo
      - rabbitmq

  product:
    build: ./product
    container_name: product
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_PRODUCT_URI=mongodb://mongo/products
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  order:
    build: ./order
    container_name: order
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_ORDER_URI=mongodb://mongo/orders
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 20s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
